[package]
name = "ad-editor"
version = "0.3.2"
edition = "2021"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/ad"
documentation = "https://docs.rs/ad-editor"
readme = "README.md"
description = "An adaptable text editor"
include = [
    "src/**/*",
    "data/**/*",
    "Cargo.toml",
    "README.md"
]
keywords = [ "terminal", "editor", "text-editor" ]
categories = [ "development-tools", "text-editors", "command-line-utilities" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = [ "crates/*" , "xtask" ]

[[bin]]
doc = false
name = "ad"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1

# For a release optimised build that is quicker to run while iterating locally
[profile.release-test]
inherits = "release"
lto = false
codegen-units = 16

[[bench]]
name = "bench_main"
harness = false

[dependencies]
ad_event = { version = "0.3", path = "crates/ad_event" }
libc = "0.2.171"
libloading = "0.8.6"
lsp-types = "0.97.0"
ninep = { version = "0.4", path = "crates/ninep", default-features = false }
serde = "1.0.219"
serde_json = "1.0.140"
streaming-iterator = "0.1.9"
toml = { version = "0.8.20", features = [ "preserve_order" ] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "fmt" ] }
tree-sitter = "0.25.3"
unicode-width = "0.2.0"

[dev-dependencies]
criterion = "0.5"
simple_test_case = "1"
simple_txtar = "1"
tree-sitter-python = "0.23.6"
tree-sitter-rust = "0.23.2"
