[package]
name = "ninep"
version = "0.3.0"
edition = "2021"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/ad/crates/ninep"
readme = "README.md"
description = "A bare bones 9p implementation"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:async-trait"]

[dependencies]
async-trait = { version = "0.1.86", optional = true }
bitflags = "2.6"
futures = "0.3.31"
tokio =  { version = "1.43.0", features = ["time", "macros", "parking_lot", "rt-multi-thread", "net", "io-util", "sync"], optional = true }

[dev-dependencies]
simple_test_case = "1"
