[package]
name = "ninep"
version = "0.5.0"
edition = "2024"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/ad/tree/develop/crates/ninep"
readme = "README.md"
description = "A bare bones 9p implementation"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
bitflags = "2"
tokio =  { version = "1", features = ["macros", "net", "io-util", "rt", "sync"], optional = true }
simple_coro = "0.1"

[dev-dependencies]
simple_test_case = "1"
tokio =  { version = "1", features = ["macros", "net", "io-util", "rt", "sync", "time", "rt-multi-thread", "net", "io-util"] }
