[package]
name = "ninep"
version = "0.4.0"
edition = "2021"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/ad/crates/ninep"
readme = "README.md"
description = "A bare bones 9p implementation"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
bitflags = "2.6"
tokio =  { version = "1.43.0", features = ["macros", "net", "io-util", "rt", "sync"], optional = true }
simple_coro = { git = "https://github.com/sminez/crimes.git", package = "crimes" }

[dev-dependencies]
simple_test_case = "1"
tokio =  { version = "1.43.0", features = ["macros", "net", "io-util", "rt", "sync", "time", "rt-multi-thread", "net", "io-util"] }
