/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_LF = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  aux_sym_variable_value_token1 = 6,
  anon_sym_data = 7,
  anon_sym_matches = 8,
  anon_sym_SPACE = 9,
  anon_sym_narrows = 10,
  anon_sym_set = 11,
  anon_sym_from = 12,
  anon_sym_is = 13,
  anon_sym_arg = 14,
  anon_sym_isfile = 15,
  anon_sym_isdir = 16,
  anon_sym_attr = 17,
  anon_sym_add = 18,
  anon_sym_delete = 19,
  anon_sym_src = 20,
  anon_sym_dst = 21,
  anon_sym_wdir = 22,
  anon_sym_plumb = 23,
  anon_sym_to = 24,
  anon_sym_start = 25,
  sym_variable_reference = 26,
  sym_value_content = 27,
  sym_source_file = 28,
  sym_comment = 29,
  sym__blank_line = 30,
  sym_variable_declaration = 31,
  sym_variable_value = 32,
  sym_rule_block = 33,
  sym_pattern = 34,
  sym_data_matches = 35,
  sym_data_narrows = 36,
  sym_data_set = 37,
  sym_data_from = 38,
  sym_field_is = 39,
  sym_field_set = 40,
  sym_field_matches = 41,
  sym_arg_isfile = 42,
  sym_arg_isdir = 43,
  sym_attr_add = 44,
  sym_attr_delete = 45,
  sym_field = 46,
  sym_match_field = 47,
  sym_action = 48,
  sym_plumb_to = 49,
  sym_plumb_start = 50,
  sym_value = 51,
  sym_command = 52,
  sym_regex = 53,
  sym_attr_list = 54,
  sym_attr_pair = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_rule_block_repeat1 = 57,
  aux_sym_rule_block_repeat2 = 58,
  aux_sym_value_repeat1 = 59,
  aux_sym_attr_list_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [aux_sym_variable_value_token1] = "variable_value_token1",
  [anon_sym_data] = "data",
  [anon_sym_matches] = "matches",
  [anon_sym_SPACE] = " ",
  [anon_sym_narrows] = "narrows",
  [anon_sym_set] = "set",
  [anon_sym_from] = "from",
  [anon_sym_is] = "is",
  [anon_sym_arg] = "arg",
  [anon_sym_isfile] = "isfile",
  [anon_sym_isdir] = "isdir",
  [anon_sym_attr] = "attr",
  [anon_sym_add] = "add",
  [anon_sym_delete] = "delete",
  [anon_sym_src] = "src",
  [anon_sym_dst] = "dst",
  [anon_sym_wdir] = "wdir",
  [anon_sym_plumb] = "plumb",
  [anon_sym_to] = "to",
  [anon_sym_start] = "start",
  [sym_variable_reference] = "variable_reference",
  [sym_value_content] = "value_content",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym__blank_line] = "_blank_line",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_value] = "variable_value",
  [sym_rule_block] = "rule_block",
  [sym_pattern] = "pattern",
  [sym_data_matches] = "data_matches",
  [sym_data_narrows] = "data_narrows",
  [sym_data_set] = "data_set",
  [sym_data_from] = "data_from",
  [sym_field_is] = "field_is",
  [sym_field_set] = "field_set",
  [sym_field_matches] = "field_matches",
  [sym_arg_isfile] = "arg_isfile",
  [sym_arg_isdir] = "arg_isdir",
  [sym_attr_add] = "attr_add",
  [sym_attr_delete] = "attr_delete",
  [sym_field] = "field",
  [sym_match_field] = "match_field",
  [sym_action] = "action",
  [sym_plumb_to] = "plumb_to",
  [sym_plumb_start] = "plumb_start",
  [sym_value] = "value",
  [sym_command] = "command",
  [sym_regex] = "regex",
  [sym_attr_list] = "attr_list",
  [sym_attr_pair] = "attr_pair",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_block_repeat1] = "rule_block_repeat1",
  [aux_sym_rule_block_repeat2] = "rule_block_repeat2",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_attr_list_repeat1] = "attr_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [aux_sym_variable_value_token1] = aux_sym_variable_value_token1,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_matches] = anon_sym_matches,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_narrows] = anon_sym_narrows,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_arg] = anon_sym_arg,
  [anon_sym_isfile] = anon_sym_isfile,
  [anon_sym_isdir] = anon_sym_isdir,
  [anon_sym_attr] = anon_sym_attr,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_delete] = anon_sym_delete,
  [anon_sym_src] = anon_sym_src,
  [anon_sym_dst] = anon_sym_dst,
  [anon_sym_wdir] = anon_sym_wdir,
  [anon_sym_plumb] = anon_sym_plumb,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_start] = anon_sym_start,
  [sym_variable_reference] = sym_variable_reference,
  [sym_value_content] = sym_value_content,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym__blank_line] = sym__blank_line,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_value] = sym_variable_value,
  [sym_rule_block] = sym_rule_block,
  [sym_pattern] = sym_pattern,
  [sym_data_matches] = sym_data_matches,
  [sym_data_narrows] = sym_data_narrows,
  [sym_data_set] = sym_data_set,
  [sym_data_from] = sym_data_from,
  [sym_field_is] = sym_field_is,
  [sym_field_set] = sym_field_set,
  [sym_field_matches] = sym_field_matches,
  [sym_arg_isfile] = sym_arg_isfile,
  [sym_arg_isdir] = sym_arg_isdir,
  [sym_attr_add] = sym_attr_add,
  [sym_attr_delete] = sym_attr_delete,
  [sym_field] = sym_field,
  [sym_match_field] = sym_match_field,
  [sym_action] = sym_action,
  [sym_plumb_to] = sym_plumb_to,
  [sym_plumb_start] = sym_plumb_start,
  [sym_value] = sym_value,
  [sym_command] = sym_command,
  [sym_regex] = sym_regex,
  [sym_attr_list] = sym_attr_list,
  [sym_attr_pair] = sym_attr_pair,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_block_repeat1] = aux_sym_rule_block_repeat1,
  [aux_sym_rule_block_repeat2] = aux_sym_rule_block_repeat2,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_attr_list_repeat1] = aux_sym_attr_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_matches] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_narrows] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_arg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isfile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isdir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_attr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_delete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_src] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wdir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_plumb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_start] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_value_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_data_matches] = {
    .visible = true,
    .named = true,
  },
  [sym_data_narrows] = {
    .visible = true,
    .named = true,
  },
  [sym_data_set] = {
    .visible = true,
    .named = true,
  },
  [sym_data_from] = {
    .visible = true,
    .named = true,
  },
  [sym_field_is] = {
    .visible = true,
    .named = true,
  },
  [sym_field_set] = {
    .visible = true,
    .named = true,
  },
  [sym_field_matches] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_isfile] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_isdir] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_add] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_delete] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_match_field] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_plumb_to] = {
    .visible = true,
    .named = true,
  },
  [sym_plumb_start] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_list] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_pair] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attr_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attr = 1,
  field_attr_value = 2,
  field_attrs = 3,
  field_command = 4,
  field_name = 5,
  field_path = 6,
  field_port = 7,
  field_regex = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr] = "attr",
  [field_attr_value] = "attr_value",
  [field_attrs] = "attrs",
  [field_command] = "command",
  [field_name] = "name",
  [field_path] = "path",
  [field_port] = "port",
  [field_regex] = "regex",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 1},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_regex, 3},
  [3] =
    {field_value, 3},
  [4] =
    {field_command, 3},
  [5] =
    {field_path, 3},
  [6] =
    {field_attrs, 3},
  [7] =
    {field_attr, 3},
  [8] =
    {field_port, 2},
  [9] =
    {field_command, 2},
  [10] =
    {field_attr, 0},
    {field_attr_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 14,
  [24] = 15,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 14,
  [30] = 15,
  [31] = 16,
  [32] = 27,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 27,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 45,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 64,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(86);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '$') ADVANCE(77);
      if (lookahead == '=') ADVANCE(97);
      if (lookahead == '\\') SKIP(79);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == 'f') ADVANCE(59);
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 'm') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(48);
      if (lookahead == 's') ADVANCE(41);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == 'w') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(21);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(21);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(94);
      if (lookahead == ' ') ADVANCE(122);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '$') ADVANCE(77);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(150);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(95);
      if (lookahead == ' ') SKIP(4);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '$') ADVANCE(77);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(151);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(22);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(22);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == ' ') ADVANCE(124);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '$') ADVANCE(77);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(153);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '#') ADVANCE(90);
      if (lookahead == '\\') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0) ADVANCE(118);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(9);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(96);
      if (lookahead == ' ') ADVANCE(123);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(10);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(23);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '\r') SKIP(12);
      END_STATE();
    case 14:
      if (lookahead == '\n') SKIP(20);
      END_STATE();
    case 15:
      if (lookahead == '\n') SKIP(20);
      if (lookahead == '\r') SKIP(14);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(92);
      if (lookahead == '\r') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(92);
      if (lookahead == '#') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(92);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == '\n') ADVANCE(91);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(125);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(15);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(20);
      END_STATE();
    case 21:
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'f') ADVANCE(59);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead == 'm') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead == 's') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      END_STATE();
    case 22:
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 23:
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(13);
      if (lookahead == 'i') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      END_STATE();
    case 24:
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '$') ADVANCE(77);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(24);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(154);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(119);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == 's') ADVANCE(68);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 30:
      if (lookahead == 'b') ADVANCE(145);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(139);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(137);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(34);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead == 'r') ADVANCE(31);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 43:
      if (lookahead == 'g') ADVANCE(131);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 51:
      if (lookahead == 'm') ADVANCE(128);
      END_STATE();
    case 52:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(147);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(135);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(143);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(134);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(121);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(129);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(141);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(127);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(148);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 76:
      if (lookahead == 'w') ADVANCE(65);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 78:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 79:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(78);
      END_STATE();
    case 80:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(82);
      END_STATE();
    case 81:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(82);
      if (lookahead == '\r') SKIP(80);
      END_STATE();
    case 82:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(81);
      if (lookahead == 'a') ADVANCE(107);
      if (lookahead == 'd') ADVANCE(99);
      if (lookahead == 's') ADVANCE(108);
      if (lookahead == 'w') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 83:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\\') SKIP(85);
      if (lookahead == 'a') ADVANCE(107);
      if (lookahead == 'd') ADVANCE(99);
      if (lookahead == 'p') ADVANCE(105);
      if (lookahead == 's') ADVANCE(108);
      if (lookahead == 'w') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 84:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(83);
      END_STATE();
    case 85:
      if (eof) ADVANCE(86);
      if (lookahead == '\n') SKIP(83);
      if (lookahead == '\r') SKIP(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '\n') ADVANCE(91);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(118);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(92);
      if (lookahead == '#') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(94);
      if (lookahead == ' ') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(150);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(151);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(96);
      if (lookahead == ' ') ADVANCE(123);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(111);
      if (lookahead == 's') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead == 't') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_variable_value_token1);
      if (lookahead == '\r') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_variable_value_token1);
      if (lookahead == '#') ADVANCE(90);
      if (lookahead == '\\') ADVANCE(116);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_variable_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_data);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_matches);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(94);
      if (lookahead == ' ') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(150);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(96);
      if (lookahead == ' ') ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(124);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(153);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_narrows);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_is);
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_arg);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_arg);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_isfile);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_isdir);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_attr);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_attr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_delete);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_src);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_src);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_dst);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_dst);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_wdir);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_wdir);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_plumb);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_plumb);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_start);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_variable_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead == '\n') ADVANCE(94);
      if (lookahead == ' ') ADVANCE(122);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead == '\n') ADVANCE(95);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(152);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead == '\r') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead == ' ') ADVANCE(124);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(154);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_value_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '$') ADVANCE(155);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 82},
  [2] = {.lex_state = 82},
  [3] = {.lex_state = 82},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 83},
  [7] = {.lex_state = 83},
  [8] = {.lex_state = 83},
  [9] = {.lex_state = 82},
  [10] = {.lex_state = 82},
  [11] = {.lex_state = 82},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 24},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 24},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 21},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 22},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 20},
  [49] = {.lex_state = 22},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 20},
  [52] = {.lex_state = 20},
  [53] = {.lex_state = 20},
  [54] = {.lex_state = 82},
  [55] = {.lex_state = 82},
  [56] = {.lex_state = 82},
  [57] = {.lex_state = 20},
  [58] = {.lex_state = 82},
  [59] = {.lex_state = 20},
  [60] = {.lex_state = 82},
  [61] = {.lex_state = 82},
  [62] = {.lex_state = 82},
  [63] = {.lex_state = 82},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 82},
  [66] = {.lex_state = 17},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 20},
  [69] = {.lex_state = 82},
  [70] = {.lex_state = 82},
  [71] = {.lex_state = 82},
  [72] = {.lex_state = 82},
  [73] = {.lex_state = 82},
  [74] = {.lex_state = 20},
  [75] = {.lex_state = 20},
  [76] = {.lex_state = 22},
  [77] = {.lex_state = 20},
  [78] = {.lex_state = 22},
  [79] = {.lex_state = 20},
  [80] = {.lex_state = 21},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 82},
  [83] = {.lex_state = 20},
  [84] = {.lex_state = 82},
  [85] = {.lex_state = 82},
  [86] = {.lex_state = 82},
  [87] = {.lex_state = 82},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 82},
  [90] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_matches] = ACTIONS(1),
    [anon_sym_narrows] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_arg] = ACTIONS(1),
    [anon_sym_isfile] = ACTIONS(1),
    [anon_sym_isdir] = ACTIONS(1),
    [anon_sym_attr] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_delete] = ACTIONS(1),
    [anon_sym_src] = ACTIONS(1),
    [anon_sym_dst] = ACTIONS(1),
    [anon_sym_wdir] = ACTIONS(1),
    [anon_sym_plumb] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_start] = ACTIONS(1),
    [sym_variable_reference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(67),
    [sym_comment] = STATE(1),
    [sym__blank_line] = STATE(10),
    [sym_variable_declaration] = STATE(10),
    [sym_rule_block] = STATE(10),
    [sym_pattern] = STATE(85),
    [sym_data_matches] = STATE(86),
    [sym_data_narrows] = STATE(86),
    [sym_data_set] = STATE(86),
    [sym_data_from] = STATE(86),
    [sym_field_is] = STATE(86),
    [sym_field_set] = STATE(86),
    [sym_field_matches] = STATE(86),
    [sym_arg_isfile] = STATE(86),
    [sym_arg_isdir] = STATE(86),
    [sym_attr_add] = STATE(86),
    [sym_attr_delete] = STATE(86),
    [sym_field] = STATE(80),
    [sym_match_field] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_rule_block_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LF] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_data] = ACTIONS(13),
    [anon_sym_arg] = ACTIONS(15),
    [anon_sym_attr] = ACTIONS(17),
    [anon_sym_src] = ACTIONS(19),
    [anon_sym_dst] = ACTIONS(19),
    [anon_sym_wdir] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_LF,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_data,
    ACTIONS(15), 1,
      anon_sym_arg,
    ACTIONS(17), 1,
      anon_sym_attr,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(4), 1,
      aux_sym_rule_block_repeat1,
    STATE(40), 1,
      sym_match_field,
    STATE(80), 1,
      sym_field,
    STATE(85), 1,
      sym_pattern,
    ACTIONS(19), 3,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
    STATE(10), 3,
      sym__blank_line,
      sym_variable_declaration,
      sym_rule_block,
    STATE(86), 11,
      sym_data_matches,
      sym_data_narrows,
      sym_data_set,
      sym_data_from,
      sym_field_is,
      sym_field_set,
      sym_field_matches,
      sym_arg_isfile,
      sym_arg_isdir,
      sym_attr_add,
      sym_attr_delete,
  [63] = 15,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_data,
    ACTIONS(34), 1,
      anon_sym_arg,
    ACTIONS(37), 1,
      anon_sym_attr,
    STATE(4), 1,
      aux_sym_rule_block_repeat1,
    STATE(40), 1,
      sym_match_field,
    STATE(80), 1,
      sym_field,
    STATE(85), 1,
      sym_pattern,
    STATE(3), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    ACTIONS(40), 3,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
    STATE(10), 3,
      sym__blank_line,
      sym_variable_declaration,
      sym_rule_block,
    STATE(86), 11,
      sym_data_matches,
      sym_data_narrows,
      sym_data_set,
      sym_data_from,
      sym_field_is,
      sym_field_set,
      sym_field_matches,
      sym_arg_isfile,
      sym_arg_isdir,
      sym_attr_add,
      sym_attr_delete,
  [124] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(43), 1,
      anon_sym_data,
    ACTIONS(45), 1,
      anon_sym_arg,
    ACTIONS(47), 1,
      anon_sym_attr,
    ACTIONS(51), 1,
      anon_sym_plumb,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_rule_block_repeat1,
    STATE(6), 1,
      aux_sym_rule_block_repeat2,
    STATE(40), 1,
      sym_match_field,
    STATE(80), 1,
      sym_field,
    STATE(82), 1,
      sym_action,
    STATE(85), 1,
      sym_pattern,
    STATE(84), 2,
      sym_plumb_to,
      sym_plumb_start,
    ACTIONS(49), 3,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
    STATE(86), 11,
      sym_data_matches,
      sym_data_narrows,
      sym_data_set,
      sym_data_from,
      sym_field_is,
      sym_field_set,
      sym_field_matches,
      sym_arg_isfile,
      sym_arg_isdir,
      sym_attr_add,
      sym_attr_delete,
  [183] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_data,
    ACTIONS(56), 1,
      anon_sym_arg,
    ACTIONS(59), 1,
      anon_sym_attr,
    ACTIONS(65), 1,
      anon_sym_plumb,
    STATE(40), 1,
      sym_match_field,
    STATE(80), 1,
      sym_field,
    STATE(85), 1,
      sym_pattern,
    STATE(5), 2,
      sym_comment,
      aux_sym_rule_block_repeat1,
    ACTIONS(62), 3,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
    STATE(86), 11,
      sym_data_matches,
      sym_data_narrows,
      sym_data_set,
      sym_data_from,
      sym_field_is,
      sym_field_set,
      sym_field_matches,
      sym_arg_isfile,
      sym_arg_isdir,
      sym_attr_add,
      sym_attr_delete,
  [230] = 8,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(71), 1,
      anon_sym_plumb,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_rule_block_repeat2,
    STATE(82), 1,
      sym_action,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(84), 2,
      sym_plumb_to,
      sym_plumb_start,
    ACTIONS(69), 7,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
  [263] = 7,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      anon_sym_plumb,
    STATE(82), 1,
      sym_action,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 2,
      sym_comment,
      aux_sym_rule_block_repeat2,
    STATE(84), 2,
      sym_plumb_to,
      sym_plumb_start,
    ACTIONS(75), 7,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
  [294] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(8), 1,
      sym_comment,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(75), 8,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
      anon_sym_plumb,
  [315] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(82), 7,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
  [335] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(86), 7,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
  [355] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(11), 1,
      sym_comment,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(90), 7,
      sym_identifier,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
  [375] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(12), 1,
      sym_comment,
    ACTIONS(65), 7,
      anon_sym_data,
      anon_sym_arg,
      anon_sym_attr,
      anon_sym_src,
      anon_sym_dst,
      anon_sym_wdir,
      anon_sym_plumb,
  [391] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      anon_sym_matches,
    ACTIONS(94), 1,
      anon_sym_narrows,
    ACTIONS(96), 1,
      anon_sym_set,
    ACTIONS(98), 1,
      anon_sym_from,
    ACTIONS(100), 1,
      anon_sym_is,
    STATE(13), 1,
      sym_comment,
  [413] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(14), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_value_repeat1,
    ACTIONS(102), 2,
      anon_sym_LF,
      anon_sym_SPACE,
    ACTIONS(104), 2,
      sym_variable_reference,
      sym_value_content,
  [431] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(106), 2,
      anon_sym_LF,
      anon_sym_SPACE,
    ACTIONS(108), 2,
      sym_variable_reference,
      sym_value_content,
    STATE(15), 2,
      sym_comment,
      aux_sym_value_repeat1,
  [447] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(14), 1,
      aux_sym_value_repeat1,
    STATE(16), 1,
      sym_comment,
    STATE(45), 1,
      sym_value,
    ACTIONS(104), 2,
      sym_variable_reference,
      sym_value_content,
  [464] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_value_repeat1,
    STATE(69), 1,
      sym_value,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [481] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_value_repeat1,
    STATE(71), 1,
      sym_value,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [498] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    STATE(20), 1,
      aux_sym_value_repeat1,
    STATE(73), 1,
      sym_command,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [515] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(113), 1,
      anon_sym_LF,
    STATE(20), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_value_repeat1,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [532] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_value_repeat1,
    STATE(58), 1,
      sym_value,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [549] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(20), 1,
      aux_sym_value_repeat1,
    STATE(22), 1,
      sym_comment,
    STATE(60), 1,
      sym_command,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [566] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(102), 1,
      anon_sym_LF,
    STATE(23), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_value_repeat1,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [583] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(106), 1,
      anon_sym_LF,
    ACTIONS(115), 2,
      sym_variable_reference,
      sym_value_content,
    STATE(24), 2,
      sym_comment,
      aux_sym_value_repeat1,
  [598] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(23), 1,
      aux_sym_value_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(62), 1,
      sym_value,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [615] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(118), 1,
      sym_identifier,
    STATE(26), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym_attr_list_repeat1,
    STATE(43), 1,
      sym_attr_pair,
    STATE(65), 1,
      sym_attr_list,
  [634] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(120), 4,
      anon_sym_LF,
      anon_sym_SPACE,
      sym_variable_reference,
      sym_value_content,
  [647] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(23), 1,
      aux_sym_value_repeat1,
    STATE(28), 1,
      sym_comment,
    STATE(63), 1,
      sym_value,
    ACTIONS(111), 2,
      sym_variable_reference,
      sym_value_content,
  [664] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    STATE(29), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym_value_repeat1,
    ACTIONS(122), 2,
      sym_variable_reference,
      sym_value_content,
  [681] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(106), 1,
      anon_sym_SPACE,
    ACTIONS(124), 2,
      sym_variable_reference,
      sym_value_content,
    STATE(30), 2,
      sym_comment,
      aux_sym_value_repeat1,
  [696] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(29), 1,
      aux_sym_value_repeat1,
    STATE(31), 1,
      sym_comment,
    STATE(83), 1,
      sym_value,
    ACTIONS(122), 2,
      sym_variable_reference,
      sym_value_content,
  [713] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_LF,
      sym_variable_reference,
      sym_value_content,
  [725] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(100), 1,
      anon_sym_is,
    STATE(33), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_matches,
      anon_sym_set,
  [739] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(118), 1,
      sym_identifier,
    STATE(34), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_attr_list_repeat1,
    STATE(44), 1,
      sym_attr_pair,
  [755] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(79), 1,
      sym_attr_pair,
    STATE(35), 2,
      sym_comment,
      aux_sym_attr_list_repeat1,
  [769] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_SPACE,
      sym_variable_reference,
      sym_value_content,
  [781] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(132), 1,
      anon_sym_add,
    ACTIONS(134), 1,
      anon_sym_delete,
    STATE(37), 1,
      sym_comment,
  [794] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(136), 1,
      aux_sym_variable_value_token1,
    STATE(38), 1,
      sym_comment,
    STATE(55), 1,
      sym_regex,
  [807] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(136), 1,
      aux_sym_variable_value_token1,
    STATE(39), 1,
      sym_comment,
    STATE(56), 1,
      sym_regex,
  [820] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(138), 1,
      anon_sym_matches,
    ACTIONS(140), 1,
      anon_sym_set,
    STATE(40), 1,
      sym_comment,
  [833] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(142), 1,
      aux_sym_variable_value_token1,
    STATE(41), 1,
      sym_comment,
    STATE(61), 1,
      sym_variable_value,
  [846] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(136), 1,
      aux_sym_variable_value_token1,
    STATE(42), 1,
      sym_comment,
    STATE(70), 1,
      sym_regex,
  [859] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(144), 1,
      anon_sym_LF,
    ACTIONS(146), 1,
      anon_sym_SPACE,
    STATE(43), 1,
      sym_comment,
  [872] = 4,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(146), 1,
      anon_sym_SPACE,
    ACTIONS(148), 1,
      anon_sym_LF,
    STATE(44), 1,
      sym_comment,
  [885] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    STATE(45), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [896] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(152), 1,
      anon_sym_isfile,
    ACTIONS(154), 1,
      anon_sym_isdir,
    STATE(46), 1,
      sym_comment,
  [909] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(156), 1,
      anon_sym_to,
    ACTIONS(158), 1,
      anon_sym_start,
    STATE(47), 1,
      sym_comment,
  [922] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(160), 1,
      anon_sym_SPACE,
    STATE(48), 1,
      sym_comment,
  [932] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(49), 1,
      sym_comment,
  [942] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(164), 1,
      anon_sym_SPACE,
    STATE(50), 1,
      sym_comment,
  [952] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(166), 1,
      anon_sym_SPACE,
    STATE(51), 1,
      sym_comment,
  [962] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(168), 1,
      anon_sym_SPACE,
    STATE(52), 1,
      sym_comment,
  [972] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(170), 1,
      anon_sym_SPACE,
    STATE(53), 1,
      sym_comment,
  [982] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      anon_sym_LF,
    STATE(54), 1,
      sym_comment,
  [992] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(174), 1,
      anon_sym_LF,
    STATE(55), 1,
      sym_comment,
  [1002] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(176), 1,
      anon_sym_LF,
    STATE(56), 1,
      sym_comment,
  [1012] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(178), 1,
      anon_sym_SPACE,
    STATE(57), 1,
      sym_comment,
  [1022] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(180), 1,
      anon_sym_LF,
    STATE(58), 1,
      sym_comment,
  [1032] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    STATE(59), 1,
      sym_comment,
  [1042] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(184), 1,
      anon_sym_LF,
    STATE(60), 1,
      sym_comment,
  [1052] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(186), 1,
      anon_sym_LF,
    STATE(61), 1,
      sym_comment,
  [1062] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_LF,
    STATE(62), 1,
      sym_comment,
  [1072] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_LF,
    STATE(63), 1,
      sym_comment,
  [1082] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(192), 1,
      anon_sym_EQ,
    STATE(64), 1,
      sym_comment,
  [1092] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(65), 1,
      sym_comment,
  [1102] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(196), 1,
      aux_sym_comment_token1,
    STATE(66), 1,
      sym_comment,
  [1112] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      sym_comment,
  [1122] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_SPACE,
    STATE(68), 1,
      sym_comment,
  [1132] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      anon_sym_LF,
    STATE(69), 1,
      sym_comment,
  [1142] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(204), 1,
      anon_sym_LF,
    STATE(70), 1,
      sym_comment,
  [1152] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(206), 1,
      anon_sym_LF,
    STATE(71), 1,
      sym_comment,
  [1162] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(208), 1,
      anon_sym_LF,
    STATE(72), 1,
      sym_comment,
  [1172] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(210), 1,
      anon_sym_LF,
    STATE(73), 1,
      sym_comment,
  [1182] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(212), 1,
      anon_sym_SPACE,
    STATE(74), 1,
      sym_comment,
  [1192] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(214), 1,
      anon_sym_SPACE,
    STATE(75), 1,
      sym_comment,
  [1202] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(76), 1,
      sym_comment,
  [1212] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(218), 1,
      anon_sym_SPACE,
    STATE(77), 1,
      sym_comment,
  [1222] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(220), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comment,
  [1232] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(222), 1,
      anon_sym_SPACE,
    STATE(79), 1,
      sym_comment,
  [1242] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(224), 1,
      anon_sym_is,
    STATE(80), 1,
      sym_comment,
  [1252] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(226), 1,
      anon_sym_EQ,
    STATE(81), 1,
      sym_comment,
  [1262] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(228), 1,
      anon_sym_LF,
    STATE(82), 1,
      sym_comment,
  [1272] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(230), 1,
      anon_sym_SPACE,
    STATE(83), 1,
      sym_comment,
  [1282] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(232), 1,
      anon_sym_LF,
    STATE(84), 1,
      sym_comment,
  [1292] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(234), 1,
      anon_sym_LF,
    STATE(85), 1,
      sym_comment,
  [1302] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(236), 1,
      anon_sym_LF,
    STATE(86), 1,
      sym_comment,
  [1312] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(238), 1,
      anon_sym_LF,
    STATE(87), 1,
      sym_comment,
  [1322] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(240), 1,
      anon_sym_EQ,
    STATE(88), 1,
      sym_comment,
  [1332] = 3,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(242), 1,
      anon_sym_LF,
    STATE(89), 1,
      sym_comment,
  [1342] = 1,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 183,
  [SMALL_STATE(6)] = 230,
  [SMALL_STATE(7)] = 263,
  [SMALL_STATE(8)] = 294,
  [SMALL_STATE(9)] = 315,
  [SMALL_STATE(10)] = 335,
  [SMALL_STATE(11)] = 355,
  [SMALL_STATE(12)] = 375,
  [SMALL_STATE(13)] = 391,
  [SMALL_STATE(14)] = 413,
  [SMALL_STATE(15)] = 431,
  [SMALL_STATE(16)] = 447,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 481,
  [SMALL_STATE(19)] = 498,
  [SMALL_STATE(20)] = 515,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 549,
  [SMALL_STATE(23)] = 566,
  [SMALL_STATE(24)] = 583,
  [SMALL_STATE(25)] = 598,
  [SMALL_STATE(26)] = 615,
  [SMALL_STATE(27)] = 634,
  [SMALL_STATE(28)] = 647,
  [SMALL_STATE(29)] = 664,
  [SMALL_STATE(30)] = 681,
  [SMALL_STATE(31)] = 696,
  [SMALL_STATE(32)] = 713,
  [SMALL_STATE(33)] = 725,
  [SMALL_STATE(34)] = 739,
  [SMALL_STATE(35)] = 755,
  [SMALL_STATE(36)] = 769,
  [SMALL_STATE(37)] = 781,
  [SMALL_STATE(38)] = 794,
  [SMALL_STATE(39)] = 807,
  [SMALL_STATE(40)] = 820,
  [SMALL_STATE(41)] = 833,
  [SMALL_STATE(42)] = 846,
  [SMALL_STATE(43)] = 859,
  [SMALL_STATE(44)] = 872,
  [SMALL_STATE(45)] = 885,
  [SMALL_STATE(46)] = 896,
  [SMALL_STATE(47)] = 909,
  [SMALL_STATE(48)] = 922,
  [SMALL_STATE(49)] = 932,
  [SMALL_STATE(50)] = 942,
  [SMALL_STATE(51)] = 952,
  [SMALL_STATE(52)] = 962,
  [SMALL_STATE(53)] = 972,
  [SMALL_STATE(54)] = 982,
  [SMALL_STATE(55)] = 992,
  [SMALL_STATE(56)] = 1002,
  [SMALL_STATE(57)] = 1012,
  [SMALL_STATE(58)] = 1022,
  [SMALL_STATE(59)] = 1032,
  [SMALL_STATE(60)] = 1042,
  [SMALL_STATE(61)] = 1052,
  [SMALL_STATE(62)] = 1062,
  [SMALL_STATE(63)] = 1072,
  [SMALL_STATE(64)] = 1082,
  [SMALL_STATE(65)] = 1092,
  [SMALL_STATE(66)] = 1102,
  [SMALL_STATE(67)] = 1112,
  [SMALL_STATE(68)] = 1122,
  [SMALL_STATE(69)] = 1132,
  [SMALL_STATE(70)] = 1142,
  [SMALL_STATE(71)] = 1152,
  [SMALL_STATE(72)] = 1162,
  [SMALL_STATE(73)] = 1172,
  [SMALL_STATE(74)] = 1182,
  [SMALL_STATE(75)] = 1192,
  [SMALL_STATE(76)] = 1202,
  [SMALL_STATE(77)] = 1212,
  [SMALL_STATE(78)] = 1222,
  [SMALL_STATE(79)] = 1232,
  [SMALL_STATE(80)] = 1242,
  [SMALL_STATE(81)] = 1252,
  [SMALL_STATE(82)] = 1262,
  [SMALL_STATE(83)] = 1272,
  [SMALL_STATE(84)] = 1282,
  [SMALL_STATE(85)] = 1292,
  [SMALL_STATE(86)] = 1302,
  [SMALL_STATE(87)] = 1312,
  [SMALL_STATE(88)] = 1322,
  [SMALL_STATE(89)] = 1332,
  [SMALL_STATE(90)] = 1342,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_block, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_block, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_block_repeat2, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_block_repeat2, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_block_repeat2, 2, 0, 0), SHIFT_REPEAT(47),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__blank_line, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__blank_line, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match_field, 1, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attr_list_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_list, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_list, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_pair, 3, 0, 10),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_matches, 4, 0, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_narrows, 4, 0, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_set, 4, 0, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_from, 4, 0, 4),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_isfile, 4, 0, 5),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_isdir, 4, 0, 5),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_add, 4, 0, 6),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [198] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_is, 4, 0, 3),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_matches, 4, 0, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_set, 4, 0, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plumb_to, 3, 0, 8),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plumb_start, 3, 0, 9),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attr_list_repeat1, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_pair, 3, 0, 10),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_value, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_delete, 4, 0, 7),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plumbing_rules(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plumbing_rules",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
