[package]
name = "ad-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
ad-editor = { path = "../", features = ["fuzz"] }

assert_fs = "1.1"
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "addr_parse"
path = "fuzz_targets/fuzz_addr_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "command_parse"
path = "fuzz_targets/fuzz_command_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "gap_buffer"
path = "fuzz_targets/fuzz_gap_buffer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "input_handling"
path = "fuzz_targets/fuzz_input_handling.rs"
test = false
doc = false
bench = false

[[bin]]
name = "plumbing_rules_fromstr"
path = "fuzz_targets/fuzz_plumbing_rules_fromstr.rs"
test = false
doc = false
bench = false

[[bin]]
name = "regex_compile"
path = "fuzz_targets/fuzz_regex_compile.rs"
test = false
doc = false
bench = false
