[package]
name = "ad_client"
version = "0.6.0"
edition = "2024"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/ad"
documentation = "https://docs.rs/ad_client"
readme = "README.md"
description = "A Rust client API for the ad text editor"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]
keywords = [ "terminal", "editor", "text-editor", ]
categories = [ "development-tools", "text-editors", "command-line-utilities" ]

[features]
default = ["tokio"]
tokio = ["dep:tokio", "ninep/tokio"]

[dependencies]
ad_event = { version = "0.5", path = "../ad_event" }
ninep = { version = "0.6", path = "../ninep", default-features = false }
tokio =  { version = "1", features = ["macros", "net", "io-util", "rt", "sync", "time"], optional = true }

[dev-dependencies]
ad-editor = { path = "../../" }
assert_fs = "1.1"
simple_test_case = "1"
tokio =  { version = "1", features = ["macros", "net", "io-util", "rt", "sync", "time", "rt-multi-thread", "net", "io-util"] }
