name: Test on FreeBSD

# Running this involves installing a packages and setting up a VM so we don't trigger it
# on every push. 
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Run tests on FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: pkg install -y rust
        run: |
          pwd
          freebsd-version
          cargo test --verbose
          rm -rf target
